hw1
prfms/Homeworks pull request #1
Opened 2024-03-02 18:06 UTC by prfms

2024-03-02 19:47 UTC, yurii-litvinov requested changes
- Папку .idea в случае .NET выкладывать не нужно
- Надо настроить GitHub Actions, чтобы проект там собирался

2024-03-02 19:47 UTC, yurii-litvinov commented on Homework1/Homework1/Program.fs
> +let fib n =
Не сокращайте идентификаторы (кроме общепринятых сокращений типа i, acc и т.п.), "fibonacci"

2024-03-02 19:47 UTC, yurii-litvinov commented on Homework1/Homework1/Program.fs
> +    let rec reverse_acc list acc =
Именуйте функции в camelCase всегда

2024-03-02 19:47 UTC, yurii-litvinov commented on Homework1/Homework1/Program.fs
> +        | h :: t -> reverse_acc t (h::acc)
`::` либо выделяется пробелами, либо нет. Я за то, чтобы выделялось.

2024-03-02 19:47 UTC, yurii-litvinov commented on Homework1/Homework1/Program.fs
> +        else generatePowersAcc (m - 1.0) (pow * 2.0) (acc @ [pow])
`@` делается за линейное время, `::` за константу, тут можно было бы немного аккуратнее

2024-03-02 19:47 UTC, yurii-litvinov commented on Homework1/Homework1/Program.fs
> +        if m = -1.0 then acc
Было бы гораздо приятнее, если бы m и n  были целыми

2024-03-02 19:47 UTC, yurii-litvinov commented on Homework1/Homework1/Program.fs
> +        | [] -> -1
Используйте option. -1 может быть принято за корректное значение

2024-03-08 20:55 UTC, DedSec256 commented on Homework1/Homework1/Program.fs
> +﻿let factorial x =
Здесь и дальше в задачах неплохо было бы валидировать параметры на корректные входные значения

2024-03-08 20:55 UTC, DedSec256 commented on Homework1/Homework1/Program.fs
> +    reverse (generatePowersAcc m (2.0 ** n) [])
можно засчитать, однако существует решение и без reverse, а за один проход

2024-03-08 20:55 UTC, DedSec256 commented on Homework1/Homework1/Program.fs
> +    let rec fibCounter x y i n =
кажется, тут можно обойтись меньшим числом параметров

2024-03-28 16:41 UTC, merged